### ISSUE TITLE
Error: Invalid CSS after "  margin: 0 1em": expected expression (e.g. 1px, bold), was "?if media

### ISSUE THREAD

**Issue by kibs21k** [arccoza/postcss-if-media#2]
Not  sure why but the compiling isn't working as expected maybe I've missed something, only wrapped it with postcss.
Here is a test repository so you can see if everything is matching as expected: 
https://github.com/lb021/test_if_media

![screen shot 2016-07-03 at 4 58 00 pm](https://cloud.githubusercontent.com/assets/8493970/16546244/56a53462-4144-11e6-90bf-95c9574f4e79.png)
![screen shot 2016-07-03 at 4 58 03 pm](https://cloud.githubusercontent.com/assets/8493970/16546245/56a807fa-4144-11e6-9dd2-3ed7a1172ef8.png)

I've also tried to use if-media with kirei-css a collection of postcss modules but it's not working there either.

**Comment by arccoza** [comment]
The problem is you are passing this through Sass before PostCSS and If-Media. Sass does not understand the additional syntax that postcss-if-media processes, ie. `?if media (min-width: 641px)`, and errors. If you process your scss with postcss-if-media first, then pass it on to Sass, you should get what you want.

To process scss with PostCSS before it is compiled to plain css you need to add [postcss-scss](https://github.com/postcss/postcss-scss), so that PostCSS doesn't choke on the Sass syntax.

If you want to process your Sass compiled css with other PostCSS plugins afterward, you can pass your css through PostCSS again with just those plugins.

**Comment by kibs21k** [comment]
Thanks so much for clearing this out! :)

**Comment by arccoza** [comment]
No problem. Working as expected?

**Comment by kibs21k** [comment]
Yes sir, working like a charm :)

**Comment by arccoza** [comment]
Jolly good.
